server:
  port: 8084
  servlet:
    context-path: /notification
spring:
  application:
    name: notification-service
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: ${SPRING_RABBITMQ_USERNAME}
    password: ${SPRING_RABBITMQ_PASSWORD}
  spring:
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: ${MAILTRAP_USERNAME}
    password: ${MAILTRAP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  frontend:
    base-url: ${FRONTEND_BASE_URL}
