services:
  postgres:
    image: postgres:16
    container_name: smarthome-postgres
    platform: linux/amd64
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - smarthome_pgdata:/var/lib/postgresql/data
      - ./infra/postgres/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 20

  auth-service:
    build: ./auth-service
    container_name: auth-service
    platform: linux/amd64
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${AUTH_DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SECURITY_JWT_ISSUER: ${JWT_ISSUER}
      SECURITY_JWT_SECRET: ${JWT_SECRET}
      SECURITY_JWT_EXPIRES_MINUTES: ${JWT_EXPIRES_MINUTES}
      APP_BOOTSTRAP_ADMIN_EMAIL: ${ADMIN_EMAIL}
      APP_BOOTSTRAP_ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"

  measurements-service:
    build: ./measurements-service
    container_name: measurements-service
    platform: linux/amd64
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${MEASUREMENTS_DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SECURITY_JWT_ISSUER: ${JWT_ISSUER}
      SECURITY_JWT_SECRET: ${JWT_SECRET}
    depends_on:
      postgres:
        condition: service_healthy
      auth-service:
        condition: service_started
    ports:
      - "8081:8081"

  home-service:
    build: ./home-service
    container_name: home-service
    platform: linux/amd64
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${HOME_DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SECURITY_JWT_ISSUER: ${JWT_ISSUER}
      SECURITY_JWT_SECRET: ${JWT_SECRET}
    depends_on:
      postgres:
        condition: service_healthy
      measurements-service:
        condition: service_started
      auth-service:
        condition: service_started
    ports:
      - "8082:8082"

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    platform: linux/amd64
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      auth-service:
        condition: service_started
      home-service:
        condition: service_started
      measurements-service:
        condition: service_started
    ports:
      - "8085:8085"

volumes:
  smarthome_pgdata:
